General:
    comment:
    seed: 2021
    fp16: True
    amp_level: O2
    precision: 16
    multi_gpu_mode: dp
    gpus: [0]
    epochs: 50
    grad_acc: 2
    frozen_bn: False
    patience: 10
    server: test #train #test
    log_path: logs/

Data: # ResNet50 | simCLR
    dataset_name: cptac_data
    data_shuffle: False
    data_dir: CPTAC/simCLR_pt_files/
    label_dir: dataset_csv/CPTAC/
    fold: 0
    nfold: 5

    train_dataloader:
        batch_size: 1
        num_workers: 4

    test_dataloader:
        batch_size: 1
        num_workers: 4

Model:
    name: TransMIL
    n_classes: 2 # 3-label as well


Optimizer:
    opt: lookahead_radam
    lr: 0.0002
    opt_eps: null
    opt_betas: null
    momentum: null
    weight_decay: 0.00001

Loss:
    base_loss: CrossEntropyLoss
